# Generated by Django 5.2.7 on 2026-04-16 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_webtemplate_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_archetype', models.CharField(max_length=80)),
                ('source_category_slug', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('locale', models.CharField(default='it', help_text="Foundation v1: only 'it' supported. Multi-locale is Phase A.7.", max_length=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL)),
                ('source_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_projects', to='catalog.webtemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_path', models.CharField(help_text="Dotted path into the content tree, e.g. 'home.headline'.", max_length=200)),
                ('value_json', models.TextField(help_text='JSON-encoded override value (text, list, dict, number).')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_overrides', to='projects.customerproject')),
            ],
            options={
                'ordering': ['key_path'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDesignTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette_primary', models.CharField(default='#0f172a', max_length=9)),
                ('palette_secondary', models.CharField(default='#f1f5f9', max_length=9)),
                ('palette_accent', models.CharField(default='#f59e0b', max_length=9)),
                ('heading_font', models.CharField(default='Space Grotesk', max_length=60)),
                ('body_font', models.CharField(default='Inter', max_length=60)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='projects.customerproject')),
            ],
            options={
                'verbose_name': 'Project design tokens',
                'verbose_name_plural': 'Project design tokens',
            },
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('manual', 'Manual save'), ('publish', 'Before publish'), ('unpublish', 'Before unpublish'), ('seed', 'Initial seed')], default='manual', max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_revisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='projects.customerproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerproject',
            index=models.Index(fields=['owner', 'status'], name='projects_cu_owner_i_81205c_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectcontent',
            constraint=models.UniqueConstraint(fields=('project', 'key_path'), name='uniq_project_content_keypath'),
        ),
    ]
