# Generated by Django 5.2.7 on 2026-05-11 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_repr', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('role_changed', 'Role changed')], db_index=True, max_length=20)),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['target_content_type', 'target_object_id'], name='core_auditl_target__b67ac5_idx'), models.Index(fields=['actor', '-timestamp'], name='core_auditl_actor_i_59358f_idx'), models.Index(fields=['action', '-timestamp'], name='core_auditl_action_d9d6a6_idx')],
            },
        ),
    ]
