# Generated by Django 5.2.7 on 2026-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('role_changed', 'Role changed'), ('order_cancelled', 'Order cancelled'), ('order_paid', 'Order paid')], db_index=True, max_length=20),
        ),
    ]
