# Generated by Django 5.2.7 on 2026-05-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlogentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('role_changed', 'Role changed'), ('order_cancelled', 'Order cancelled'), ('order_paid', 'Order paid'), ('order_fulfillment_changed', 'Order fulfillment changed'), ('project_published', 'Project published'), ('project_unpublished', 'Project unpublished')], db_index=True, max_length=32),
        ),
    ]
