# Generated by Django 5.2.7 on 2026-04-14 09:21

import apps.commerce.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_webtemplate_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('line1', models.CharField(max_length=240)),
                ('line2', models.CharField(blank=True, max_length=240)),
                ('city', models.CharField(max_length=140)),
                ('postal_code', models.CharField(max_length=40)),
                ('region', models.CharField(blank=True, max_length=140)),
                ('country', models.CharField(default='Italia', max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('est_delivery_days', models.CharField(blank=True, help_text="e.g. '48 ore in Italia · 4 giorni in Europa'.", max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(db_index=True, default=apps.commerce.models._generate_reference, max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='unpaid', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Unfulfilled'), ('packing', 'Packing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned')], db_index=True, default='unfulfilled', max_length=20)),
                ('customer_note', models.TextField(blank=True)),
                ('seller_note', models.TextField(blank=True)),
                ('tracking_carrier', models.CharField(blank=True, max_length=80)),
                ('tracking_number', models.CharField(blank=True, max_length=140)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('billing_address', models.ForeignKey(blank=True, help_text='If null, shipping address doubles as billing.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_billed_to', to='commerce.address')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_shipped_to', to='commerce.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.shippingmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('awaiting_transfer', 'Awaiting transfer'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text="Sub-head rendered on product detail (e.g. 'Cuoio del Valdarno · cucito a sella').", max_length=240)),
                ('short_description', models.CharField(blank=True, max_length=320)),
                ('long_description', models.TextField(blank=True)),
                ('sku_root', models.CharField(blank=True, max_length=40)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Shown as strike-through if > base_price.', max_digits=10, null=True)),
                ('badge', models.CharField(blank=True, help_text='Pezzo unico · Edizione · Drop 01 · Atelier · etc.', max_length=40)),
                ('edition_number', models.CharField(blank=True, max_length=40)),
                ('material', models.CharField(blank=True, max_length=160)),
                ('made_in', models.CharField(blank=True, max_length=140)),
                ('creator_name', models.CharField(blank=True, help_text='Bottega: artisan name. Luxe: atelier / textile house.', max_length=140)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero_image_url', models.URLField(blank=True)),
                ('info_rows', models.JSONField(blank=True, default=list)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='commerce.collection')),
            ],
            options={
                'ordering': ['order', '-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commerce.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('option1', models.CharField(blank=True, max_length=80)),
                ('option2', models.CharField(blank=True, max_length=80)),
                ('option3', models.CharField(blank=True, max_length=80)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='commerce.product')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=200)),
                ('variant_title', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='commerce.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='commerce.productvariant')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skin', models.CharField(choices=[('artisan-workshop', 'Artisan Workshop'), ('fashion-editorial', 'Fashion Editorial')], max_length=40)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('currency_symbol', models.CharField(default='€', max_length=4)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('payment_provider', models.CharField(choices=[('stub', 'Stub (auto-confirm, dev)'), ('offline_bank_transfer', 'Offline bank transfer')], default='stub', max_length=40)),
                ('shipping_policy', models.TextField(blank=True, help_text='Shown on product + cart + checkout pages.')),
                ('return_policy', models.TextField(blank=True)),
                ('bank_transfer_instructions', models.TextField(blank=True, help_text='Rendered on order confirmation when offline_bank_transfer is the provider.')),
                ('is_operational', models.BooleanField(default=False, help_text='Commerce-side shippability gate. A storefront must be operational before its /shop/ routes resolve publicly.')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storefront', to='catalog.webtemplate')),
            ],
            options={
                'ordering': ['template__name'],
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='commerce.storefront'),
        ),
        migrations.AddField(
            model_name='product',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='commerce.storefront'),
        ),
        migrations.AddField(
            model_name='order',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commerce.storefront'),
        ),
        migrations.AddField(
            model_name='collection',
            name='storefront',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='commerce.storefront'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='commerce.storefront')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='commerce.productvariant')),
            ],
            options={
                'ordering': ['pk'],
                'unique_together': {('cart', 'variant')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='shippingmethod',
            unique_together={('storefront', 'code')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['storefront', 'status'], name='commerce_pr_storefr_75c644_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['storefront', 'featured'], name='commerce_pr_storefr_79f41f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('storefront', 'slug')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['storefront', 'status'], name='commerce_or_storefr_f60f37_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['storefront', '-created_at'], name='commerce_or_storefr_88e3dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('storefront', 'slug')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['storefront', 'session_key', 'is_active'], name='commerce_ca_storefr_70ff84_idx'),
        ),
    ]
