# Generated by Django 5.2.7 on 2026-04-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Da preparare'), ('packing', 'In preparazione'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('returned', 'Reso')], db_index=True, default='unfulfilled', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Da pagare'), ('paid', 'Pagato'), ('refunded', 'Rimborsato'), ('failed', 'Fallito')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'In attesa'), ('confirmed', 'Confermato'), ('shipped', 'Spedito'), ('delivered', 'Consegnato'), ('cancelled', 'Annullato')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='status',
            field=models.CharField(choices=[('initiated', 'Avviato'), ('awaiting_transfer', 'In attesa di bonifico'), ('succeeded', 'Riuscito'), ('failed', 'Fallito'), ('cancelled', 'Annullato')], default='initiated', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Bozza'), ('active', 'Attivo'), ('archived', 'Archiviato')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='storefront',
            name='payment_provider',
            field=models.CharField(choices=[('stub', 'Stub · auto-conferma (dev)'), ('offline_bank_transfer', 'Bonifico bancario')], default='stub', max_length=40),
        ),
    ]
