# Generated by Django 5.2.7 on 2026-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_commerce_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefrontmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
