# Generated by Django 5.2.7 on 2026-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webtemplate',
            name='tier',
            field=models.CharField(choices=[('published_live', 'Published Live'), ('draft', 'Draft')], db_index=True, default='draft', help_text='Public tier per D-055. `published_live` templates appear in the public catalog; `draft` templates are hidden and reachable only by staff via the `?preview=1` query string.', max_length=20),
        ),
    ]
