# Generated by Django 5.2.7 on 2026-04-20 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_webtemplate_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('palette_family', models.CharField(blank=True, help_text="e.g. 'warm', 'cool', 'dark', 'noir', 'neutral'.", max_length=40)),
                ('typography_stack', models.CharField(blank=True, help_text="e.g. 'serif-editorial', 'sans-modern', 'mono-tech'.", max_length=60)),
                ('density_profile', models.CharField(blank=True, help_text="e.g. 'editorial-sparse', 'dashboard-dense', 'minimal-card'.", max_length=40)),
                ('badge', models.CharField(blank=True, help_text="Optional marker shown in catalog cards, e.g. 'new', 'popular'.", max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='audience',
            field=models.JSONField(blank=True, default=list, help_text="Array of audience slugs (e.g. ['freelance', 'smb', 'agency', 'enterprise']). Drives the 'Per ruolo' discovery block."),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_blog',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_booking',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_portfolio',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_rtl',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_shop',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='has_video',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='is_multi_page',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='price_tier',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], db_index=True, help_text='Catalog filter bucket — coarser than the numeric `price`.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='search_keywords',
            field=models.TextField(blank=True, default='', help_text='Space-separated terms fed into the typeahead endpoint as additional prefix-match candidates. Plain text, lowercase, accent-insensitive matching is done at query time.'),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='use_cases',
            field=models.JSONField(blank=True, default=list, help_text="Array of use-case slugs (e.g. ['online-ordering', 'reservations', 'menu-digital']). Surfaced as catalog filter + role/use-case discovery pages."),
        ),
        migrations.CreateModel(
            name='ProfessionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name (Bootstrap / FontAwesome).', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('search_aliases', models.TextField(blank=True, default='', help_text="Space-separated alias terms for typeahead prefix matching (e.g. 'chef stellato haute-cuisine ristorante-gourmet').")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profession_clusters', to='catalog.category')),
            ],
            options={
                'ordering': ['category__order', 'category__name', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='profession_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.professioncluster'),
        ),
        migrations.AddField(
            model_name='webtemplate',
            name='visual_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.visualstyle'),
        ),
        migrations.AddIndex(
            model_name='professioncluster',
            index=models.Index(fields=['is_active', 'category'], name='catalog_pro_is_acti_4aa224_idx'),
        ),
    ]
