# Generated by Django 5.2.7 on 2026-04-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_taxonomy_v2_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtemplate',
            name='profession_cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.professioncluster'),
        ),
        migrations.AlterField(
            model_name='webtemplate',
            name='visual_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='catalog.visualstyle'),
        ),
    ]
